version: "3.8"

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: standup
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - standup-logger-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      ENVIRONMENT: test
    ports:
      - "8081:8080"
    volumes:
      - .:/standup-logger-app
    command: ["./standup-logger"]
    networks:
      - standup-logger-net

volumes:
  postgres_data:

networks:
  standup-logger-net:
    external: true
